djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path(route='about/', view=views.about_view, name='about-us'),
    # path for contact us view
    path(route='contact/', view=views.contact_view, name='contact-us'),
    # path for registration
    path(route='registration/', view=views.registration_view, name='registration'),
    # path for login
    path(route='login/', view=views.login_view, name='login'),
    # path for logout
    path(route='logout/', view=views.logout_view, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view
    path(route='dealer/<int:dealer_id>', view=views.get_dealer_details, name='dealer_details'),

    # path for add a review view
    path(route='dealer/add-review/<int:dealer_id>', view=views.add_review, name="add_review")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/urls.py
# example/urls.py
from django.urls import path

from example.views import index


urlpatterns = [
    path('', index),
]

vercel_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example.urls')),
]

djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):

    name = models.CharField(null=False, max_length=30, default="Car Maker")
    description = models.TextField(max_length=1000)

    def dealer_id(self):
        car_models = self.carmodel_set.all()
        if car_models.exists():
            return car_models.first().dealer_id
        else:
            return None

    def __str__(self):
        return self.name


class CarModel(models.Model):

    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    dealer_id = models.IntegerField(default=0)
    name = models.CharField(max_length=200, default="Model")

    SEDAN = "sedan"
    SUV = "suv"
    WAGON = "wagon"
    COUPE = "coupe"

    TYPE_CHOICES = [
        (SEDAN, "Sedan"),
        (SUV, "Suv"),
        (WAGON, "Wagon"),
        (COUPE, "Coupe")
    ]

    car_type = models.CharField(
        null=False,
        max_length=20,
        choices=TYPE_CHOICES,
        default=SEDAN
    )

    car_year = models.DateField(null=True)

    def __str__(self):
        return self.name

class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, state, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer state
        self.state = state
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return self.full_name



class DealerReview:

    def __init__(self, dealership, name, purchase, review, id, purchase_date, car_make, car_model, car_year, sentiment):
        # Review Dealership
        self.dealership = dealership
        # User Name
        self.name = name
        # Purchase Status
        self.purchase = purchase
        # User Review
        self.review = review
        # Review Id
        self.id = id
        # Purchase Date
        self.purchase_date = purchase_date
        # Car Make
        self.car_make = car_make
        # Car Model
        self.car_model = car_model
        # Car Year
        self.car_year = car_year
        # User Sentiment
        self.sentiment = sentiment

        def __str__(self):
            return self.review

djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarModel, CarDealer
from .restapis import get_dealers_from_cf, get_dealer_reviews_from_cf, post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create an `about` view to render a static about page

def about_view(request):
    endpoint = request.path
    context = {'endpoint': endpoint}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page

def contact_view(request):
    endpoint = request.path
    context = {'endpoint': endpoint}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request

def login_view(request):
    context={}
    url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-dealership"
    dealerships = get_dealers_from_cf(url)
    context["dealership_list"]=dealerships
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'djangoapp/index.html', context)
        else:
            return render(request, 'djangoapp/index.html', context)
    else:
        return render(request, 'djangoapp/index.html', context)

# Create a `logout_request` view to handle sign out request

def logout_view(request):
    context={}
    url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-dealership"
    dealerships = get_dealers_from_cf(url)
    # Concat all dealer's short name
    context["dealership_list"]=dealerships
    logout(request)
    return render(request, 'djangoapp/index.html', context)


# Create a `registration_request` view to handle sign up request

def registration_view(request):
    context = {}
    if request.method == "GET":
        return render(request, "djangoapp/registration.html", context)
    elif request.method == "POST":
        # Check if user exists
        username = request.POST["username"]
        password = request.POST["psw"]
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]
        user_exist = False
        try:
            User.objects.get(username = username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username = username, first_name = first_name, 
                                            last_name = last_name, password = password)
            login(request, user)
            return render(request, 'djangoapp/index.html', context)
        else:
            return render(request, 'djangoapp/index.html', context)
      

# Update the `get_dealerships` view to render the index page with a list of dealerships

def get_dealerships(request):

    if request.method == "GET":

        context = {}

        st = request.GET.get("st")
        dealerId = request.GET.get("dealerId")
        url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-dealership"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)

        if st:
            dealerships = get_dealers_from_cf(url, st=st)
        elif dealerId:
            dealerId = int(dealerId)
            dealerships = get_dealers_from_cf(url, dealerId=dealerId)

        context["dealership_list"] = dealerships

        return render(request, "djangoapp/index.html", context=context)


# Create a `get_dealer_details` view to render the reviews of a dealer

def get_dealer_details(request, dealer_id):

    if request.method == "GET":
        context = {}
        dealer_url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-review"
        
        dealer = get_dealer_reviews_from_cf(dealer_url, dealer_id)
       
        context = {
            "reviews": dealer,
            "dealer_id": dealer_id,
        }      
        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review

def add_review(request, dealer_id):
    if request.method == "GET":
        cars = CarModel.objects.filter(dealer_id=dealer_id)
        context = { "cars": cars, "dealer_id": dealer_id }
        return render(request, "djangoapp/add_review.html", context)
    
    if request.method == "POST":
        carId = request.POST.get("car")
        car = CarModel.objects.get(id=carId)
        purchase = "false"
        if request.POST.get("purchasecheck") == "on":
            purchase = "true"
        review_data = request.POST
        review = {"review": {}}
        review["review"]["time"] = datetime.utcnow().isoformat()
        review["review"]["dealership"] = dealer_id
        review["review"]["review"] = review_data.get("content", "")
        review["review"]["name"] = request.user.first_name
        review["review"]["purchase"] = purchase
        review["review"]["purchase_date"] = review_data.get("purchasedate", "")
        review["review"]["car_make"] = car.car_make.name
        review["review"]["car_model"] = car.name
        review["review"]["car_year"] = car.car_year.strftime("%Y")

        response = post_request(
            "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/post-review",
            review,
            dealerId=dealer_id
        )
        
        return redirect("djangoapp:dealer_details", dealer_id=dealer_id)
       

djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>About Us</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    </head>
    body>

    {% include 'navBar.html' %}

    <h1>
        Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
        </h1>

        {% include 'footer.html' %}
</body>
</html>

djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
<body>

    {% include 'navBar.html' %}
    <!--Add review form here -->

    {% block content %}
    <body>
        <main class="container mt-5">
            <h3>Add a review about this Car Dealership</h3>
            <hr>
            <br>
            <form action="{% url 'djangoapp:add_review' dealer_id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="content"><b>Enter the review content:</b></label>
                    <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
                </div>
                <div class="form-group form-check">
                    <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                    <label for="purchasecheck">Did you purchase a car here? </label>
                </div>
                <div class="form-group">
                    <label for="car">Select your car:</label>
                    <select name="car" id="car" class="form-select">
                        {% for car in cars %}
                            <option selected value={{car.id}}>{{car.name}} - {{car.car_make}} - {{ car.car_year|date:"Y" }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group" data-provide="datepicker">
                    <label for="purchasedate">Select your purchase date (mm/dd/yyyy):</label>
                    <input class="date-own form-control" type="text" name="purchasedate" id="purchasedate">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </main>
        <script type="text/javascript">
            $('.date-own').datepicker({
               format: 'mm/dd/yyyy'
             });
       </script>
{% endblock %}

{% include 'footer.html' %}
    </body>
</html>

djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
	<head>
        <meta charset="UTF-8">
        <title>Contact Us</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="style.css">
    </head>

{% include 'navBar.html' %}

<h1>
   Contact us
	</h1>

	<div class="content">

		<div class="container">
		  <div class="row align-items-stretch no-gutters contact-wrap">
			<div class="col-md-6">
			  <div class="form h-100">
				<h3>Send us a message</h3>
				<form class="mb-5" method="post" id="contactForm" name="contactForm">
				  <div class="row">
					<div class="col-md-6 form-group mb-5">
					  <label for="" class="col-form-label">Name *</label>
					  <input type="text" class="form-control" name="name" id="name" placeholder="Your name">
					</div>
					<div class="col-md-6 form-group mb-5">
					  <label for="" class="col-form-label">Email *</label>
					  <input type="text" class="form-control" name="email" id="email"  placeholder="Your email">
					</div>
				  </div>
	
				  <div class="row">
					<div class="col-md-6 form-group mb-5">
					  <label for="" class="col-form-label">Phone</label>
					  <input type="text" class="form-control" name="phone" id="phone"  placeholder="Phone #">
					</div>
					<div class="col-md-6 form-group mb-5">
					  <label for="" class="col-form-label">Company</label>
					  <input type="text" class="form-control" name="company" id="company"  placeholder="Company  name">
					</div>
				  </div>
	
				  <div class="row">
					<div class="col-md-12 form-group mb-5">
					  <label for="message" class="col-form-label">Message *</label>
					  <textarea class="form-control" name="message" id="message" cols="30" rows="4"  placeholder="Write your message"></textarea>
					</div>
				  </div>
				  <div class="row">
					<div class="col-md-12 form-group">
					  <input type="submit" value="Send Message" class="btn btn-primary rounded-0 py-2 px-4">
					  <span class="submitting"></span>
					</div>
				  </div>
				</form>
	
			  </div>
			</div>
			</div>
		  </div>
		</div>
	
	  </div>

	  <!-- Footer -->
	  {% include 'footer.html' %}
</body>
</html>

djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>

    {% include 'navBar.html' %}

<!-- Add reviews as cards -->
{% block content %}
{% if reviews %}
    {% if user.is_authenticated %}
        <div style="margin: 10px;">
            <a class="btn btn-primary" href="{% url 'djangoapp:add_review' dealer_id %}"><b>Write a car review</b></a>
        </div>
    {% endif %}
    <div class="card-columns">
        {% for review in reviews %}
            {% if review.car_make %}
            <div class="card" style="height: 300px; overflow: scroll; overflow-x: hidden;">
                <img src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" class="card-img-left" style="float: left; height: 40px; width: 40px; display: inline-block;">
                <div class="card-body" style="text-align: center;">
                    <h5 class="card-title" style="display: inline-block;">{{ review.car_make }}, {{ review.car_model }}</h5>
                    <h5 class="card-title">{{ review.car_year }}</h5>
                    <p class="card-text" style="text-align: left;">{{ review.review }}</p>
                </div>
            </div>
            <!-- some review data may be missing , using default values-->
            {% else %}
            <div class="card" style="height: 300px; overflow: scroll; overflow-x: hidden;">
                <img src="{{MEDIA_URL}}/emoji/{{review.sentiment}}.png" class="card-img-left" style="float: left; height: 40px; width: 40px; display: inline-block;">
                <div class="card-body" style="text-align: center;">
                    <h5 class="card-title" style="display: inline-block;">Review</h5>
                    <h5 class="card-title"></h5>
                    <p class="card-text" style="text-align: left;">{{ review.review }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

{% else %}
    <p></br>There are no reviews for this dealership.</br></p>
    {% if user.is_authenticated %}
        <div style="margin: 10px;">
            <a class="btn btn-primary" href="{% url 'djangoapp:add_review' dealer_id %}"><b>Write a car review</b></a>
        </div>
    {% endif %}
{% endif %}
{% endblock %}

{% include 'footer.html' %}
</body>

</html>

djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Dealership Review</title>
</head>
<body>
  {% include 'navBar.html' %}
<div class="container">
  <table class="table table-striped" id="table" data-filter-control="true" style="margin-top: 3%; margin-bottom: 3%;">
     <thead>
             <tr>
                 <th scope="col">ID</th>
                 <th scope="col">Dealer Name</th>
                 <th scope="col">City</th>
                 <th scope="col">Address</th>
                 <th scope="col">Zip</th>
                 <th data-field="state" data-filter-control="select">State</th>
             </tr>
         </thead>
     <tbody>
         {% for dealer in dealership_list%}
             <tr>
                 <td style="padding: 2%;">{{dealer.id}}</td>
                 <td style="padding: 2%;"><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                 <td style="padding: 2%;">{{dealer.city}}</td>
                 <td style="padding: 2%;">{{dealer.address}}</td>
                 <td style="padding: 2%;">{{dealer.zip}}</td>
                 <td style="padding: 2%;">{{dealer.st}}</td>
             </tr>
         {% endfor %}
     </tbody>
 </table>
 </div>
  </body>

  <script>
      $(function() {
          $('#table').bootstrapTable()
      })
  </script>

{% include 'footer.html' %}
</html>

djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="#">Best Cars</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
<ul class="navbar-nav">
  <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="/djangoapp/about">About Us</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="/djangoapp/contact">Contact Us</a>
  </li>
  {% if user.is_authenticated %}
  <li>
      <a class="btn btn-link" href="#">{{ user.first_name }}{{ user.username }}</a>
      <a class="btn btn-link" href="logout/">Logout</a>
  </li>
  {% else %}
      <li>
              <a class="btn btn-link" href="/djangoapp/login/">Sign In</a>
              <a class="btn btn-link" href="/djangoapp/signup/">Sign Up</a>
      </li>
  {% endif %}
</ul>
</div>
</nav>
<form action="{% url 'djangoapp:registration' %}" method="post">
<div class="container">
<h1>Sign Up</h1>
<hr>
<label for="username"><b>User Name</b></label>
<input type="text" placeholder="Enter User Name: " name="username" required>
<label for="firstname"><b>First Name</b></label>
<input type="text" placeholder="Enter First Name: " name="firstname" required>
<label for="lastname"><b>Last Name</b></label>
<input type="text" placeholder="Enter Last Name: " name="lastname" required>
<label for="psw"><b>Password</b></label>
<input type="password" placeholder="Enter Password: " name="psw" required>
<div>
  {% csrf_token %}
  <button class="button" type="submit">Sign Up</button>
</div>
</div>
</form>

{% include 'footer.html' %}
</body>
</html>