djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path(route='about/', view=views.about_view, name='about-us'),
    # path for contact us view
    path(route='contact/', view=views.contact_view, name='contact-us'),
    # path for registration
    path(route='registration/', view=views.registration_view, name='registration'),
    # path for login
    path(route='login/', view=views.login_view, name='login'),
    # path for logout
    path(route='logout/', view=views.logout_view, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view
    path(route='dealer/<int:dealer_id>', view=views.get_dealer_details, name='dealer_details'),

    # path for add a review view
    path(route='dealer/add-review/<int:dealer_id>', view=views.add_review, name="add_review")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/urls.py
# example/urls.py
from django.urls import path

from example.views import index


urlpatterns = [
    path('', index),
]

vercel_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example.urls')),
]

djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):

    name = models.CharField(null=False, max_length=30, default="Car Maker")
    description = models.TextField(max_length=1000)

    def dealer_id(self):
        car_models = self.carmodel_set.all()
        if car_models.exists():
            return car_models.first().dealer_id
        else:
            return None

    def __str__(self):
        return self.name


class CarModel(models.Model):

    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    dealer_id = models.IntegerField(default=0)
    name = models.CharField(max_length=200, default="Model")

    SEDAN = "sedan"
    SUV = "suv"
    WAGON = "wagon"
    COUPE = "coupe"

    TYPE_CHOICES = [
        (SEDAN, "Sedan"),
        (SUV, "Suv"),
        (WAGON, "Wagon"),
        (COUPE, "Coupe")
    ]

    car_type = models.CharField(
        null=False,
        max_length=20,
        choices=TYPE_CHOICES,
        default=SEDAN
    )

    car_year = models.DateField(null=True)

    def __str__(self):
        return self.name

class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, state, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer state
        self.state = state
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return self.full_name



class DealerReview:

    def __init__(self, dealership, name, purchase, review, id, purchase_date, car_make, car_model, car_year, sentiment):
        # Review Dealership
        self.dealership = dealership
        # User Name
        self.name = name
        # Purchase Status
        self.purchase = purchase
        # User Review
        self.review = review
        # Review Id
        self.id = id
        # Purchase Date
        self.purchase_date = purchase_date
        # Car Make
        self.car_make = car_make
        # Car Model
        self.car_model = car_model
        # Car Year
        self.car_year = car_year
        # User Sentiment
        self.sentiment = sentiment

        def __str__(self):
            return self.review

djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarModel, CarDealer
from .restapis import get_dealers_from_cf, get_dealer_reviews_from_cf, post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create an `about` view to render a static about page

def about_view(request):
    endpoint = request.path
    context = {'endpoint': endpoint}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page

def contact_view(request):
    endpoint = request.path
    context = {'endpoint': endpoint}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request

def login_view(request):
    context={}
    url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-dealership"
    dealerships = get_dealers_from_cf(url)
    context["dealership_list"]=dealerships
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'djangoapp/index.html', context)
        else:
            return render(request, 'djangoapp/index.html', context)
    else:
        return render(request, 'djangoapp/index.html', context)

# Create a `logout_request` view to handle sign out request

def logout_view(request):
    context={}
    url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-dealership"
    dealerships = get_dealers_from_cf(url)
    # Concat all dealer's short name
    context["dealership_list"]=dealerships
    logout(request)
    return render(request, 'djangoapp/index.html', context)


# Create a `registration_request` view to handle sign up request

def registration_view(request):
    context = {}
    if request.method == "GET":
        return render(request, "djangoapp/registration.html", context)
    elif request.method == "POST":
        # Check if user exists
        username = request.POST["username"]
        password = request.POST["psw"]
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]
        user_exist = False
        try:
            User.objects.get(username = username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username = username, first_name = first_name, 
                                            last_name = last_name, password = password)
            login(request, user)
            return render(request, 'djangoapp/index.html', context)
        else:
            return render(request, 'djangoapp/index.html', context)
      

# Update the `get_dealerships` view to render the index page with a list of dealerships

def get_dealerships(request):

    if request.method == "GET":

        context = {}

        st = request.GET.get("st")
        dealerId = request.GET.get("dealerId")
        url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-dealership"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)

        if st:
            dealerships = get_dealers_from_cf(url, st=st)
        elif dealerId:
            dealerId = int(dealerId)
            dealerships = get_dealers_from_cf(url, dealerId=dealerId)

        context["dealership_list"] = dealerships

        return render(request, "djangoapp/index.html", context=context)


# Create a `get_dealer_details` view to render the reviews of a dealer

def get_dealer_details(request, dealer_id):

    if request.method == "GET":
        context = {}
        dealer_url = "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/get-review"
        
        dealer = get_dealer_reviews_from_cf(dealer_url, dealer_id)
       
        context = {
            "reviews": dealer,
            "dealer_id": dealer_id,
        }      
        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review

def add_review(request, dealer_id):
    if request.method == "GET":
        cars = CarModel.objects.filter(dealer_id=dealer_id)
        context = { "cars": cars, "dealer_id": dealer_id }
        return render(request, "djangoapp/add_review.html", context)
    
    if request.method == "POST":
        carId = request.POST.get("car")
        car = CarModel.objects.get(id=carId)
        purchase = "false"
        if request.POST.get("purchasecheck") == "on":
            purchase = "true"
        review_data = request.POST
        review = {"review": {}}
        review["review"]["time"] = datetime.utcnow().isoformat()
        review["review"]["dealership"] = dealer_id
        review["review"]["review"] = review_data.get("content", "")
        review["review"]["name"] = request.user.first_name
        review["review"]["purchase"] = purchase
        review["review"]["purchase_date"] = review_data.get("purchasedate", "")
        review["review"]["car_make"] = car.car_make.name
        review["review"]["car_model"] = car.name
        review["review"]["car_year"] = car.car_year.strftime("%Y")

        response = post_request(
            "https://us-south.functions.appdomain.cloud/api/v1/web/7ccc880f-504c-4f24-a816-b01352454616/dealership-package/post-review",
            review,
            dealerId=dealer_id
        )
        
        return redirect("djangoapp:dealer_details", dealer_id=dealer_id)
       

djangoapp/templates/footer.html
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  <!-- Footer -->

djangoapp/templates/navBar.html
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/djangoapp">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about">About us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact">Contact us</a>
              </li>
              

            </ul>
            {% if user.is_authenticated %}
            <a class="btn btn-link" href="#"
            >{{ user.first_name }}({{ user.username }})</a
          >
          <a class="btn btn-link" href="{% url 'djangoapp:logout' %}"
            >Logout</a
          >
            {% else %}
            <form
            class="form-inline"
            action="{% url 'djangoapp:login' %}"
            method="post"
          >
            {% csrf_token %}
            <div class="input-group">
              <input
                type="text"
                class="form-control"
                placeholder="Username"
                name="username"
              />
              <input
                type="password"
                class="form-control"
                placeholder="Password"
                name="password"
              />
              <button class="btn btn-primary" type="submit">Login</button>
              <a
                class="btn btn-link"
                href="{% url 'djangoapp:registration' %}"
                >Sign Up</a
              >
            </div>
          </form>

            {% endif %}
          </div>
    </nav>
 